version: '3'

services:
    app:
        container_name: app_go
        build: .
        tty: true
        volumes:
            - ./src:/app
        ports:
            - 12347:12347
        depends_on: 
            - db
    db:
        image: mysql:5.7
        container_name: mysql_host
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_database
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            TZ: 'Asia/Tokyo'
        volumes:
            - ./db/data:/var/lib/mysql
            - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306
        # command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci これ意味なくない？